# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sdK5HNg2XT0TB9xCStoV0q2NbFjsLxgW
"""

# 1. Necessary Libraries Import karein
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# 2. Dataset Load karein (Seaborn mein inbuilt hota hai)
df = sns.load_dataset('titanic')

# 3. Data Cleaning (Handling Missing Values)
# Age mein jo khali jagah hai wahan average age bhar dein
df['age'] = df['age'].fillna(df['age'].mean())
# 'deck' column mein bahut data missing hota hai, isliye ise hata dein
df.drop(columns=['deck'], inplace=True)

# 4. Data Inspection (Ye report mein kaam aayega)
print("Dataset ki shuruat ke 5 rows:")
print(df.head())
print("\nMissing values check:")
print(df.isnull().sum())

# 5. Visualizations (Main Task)
plt.figure(figsize=(15, 5))

# Plot 1: Survival rate by Gender (Kisne zyada survive kiya?)
plt.subplot(1, 3, 1)
sns.barplot(x='sex', y='survived', data=df, palette='viridis')
plt.title('Survival by Gender')

# Plot 2: Survival rate by Class (Rich vs Poor survival)
plt.subplot(1, 3, 2)
sns.barplot(x='class', y='survived', data=df, palette='magma')
plt.title('Survival by Class')

# Plot 3: Age Distribution (Passengers ki age kya thi?)
plt.subplot(1, 3, 3)
sns.histplot(df['age'], kde=True, color='blue')
plt.title('Age Distribution of Passengers')

plt.tight_layout()
plt.show()

# 6. Final Insights
print("\n--- Key Insights from Data ---")
print("1. Females had a significantly higher survival rate than males.")
print("2. Passengers in First Class had the best chance of survival.")
print("3. The majority of passengers were between 20-35 years old.")
